# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 05a5c37eda59c7f55a825891f8cc47c7122c3a5ac9c55f04e7e3f92d329f6f827c17e5a61d8120355165775d7374bddee3a0932c486533f24ca4f4c27dd4e30c

test:
  secret_key_base: b83355401821bc455346d8395b4a3ee4ec0d39596245335d0648378bc438ef8b33a816f8e95e7846bee8afed0668a95498e3e33560a5648ef1e0072facb71c8f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
